# Generated by Django 6.0.3 on 2026-03-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_mail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.SlugField(default='send', verbose_name='Статус'),
        ),
    ]
