# Generated by Django 6.0.3 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='old_status',
            field=models.SlugField(default=models.SlugField(default='sent', verbose_name='Статус'), verbose_name='Начальный статус'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.SlugField(default='sent', verbose_name='Статус'),
        ),
    ]
