# Generated by Django 6.0.3 on 2026-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_old_status_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='old_status',
            field=models.SlugField(verbose_name='Начальный статус'),
        ),
    ]
