# Generated by Django 6.0.3 on 2026-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_mail_old_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Письма', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='old_status',
            field=models.SlugField(default='', verbose_name='Начальный статус'),
        ),
    ]
