# Generated by Django 6.0.3 on 2026-03-30 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_mail_options_alter_mail_old_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Статус прочтения'),
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Получатель(связ.)'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель(связ.)'),
        ),
    ]
